# Tidy modelling with tidymodels

```{r, include=FALSE}
library(tidyverse)
```

The prediction chapter has shown us how to fit and assess the performance
of the linear model, regression trees, random forests and neural networks.

In each case both the model fitting and obtaining predictions was consistent:

- We use a formula syntax to specify the model and provide the training data.
- We use the `predict` command on the resulting model object, providing testing data.

This works well as long as all our models follow this same syntax. Unfortunately,
many models require different syntaxes for one or both of these steps.

In addition, there are often additional things that we may want to do, such as
processing the data beforehand (e.g. to scale predictors to a common scale, impute
missing values etc). Any data transformation we perform on the training set will
need to be replicated exactly on the test set. Further, the tools we've used for
summarising model performance (computing MSE via `dplyr::summarise()`) are metric-specific,
and it would be nice to be able to easily switch to other metrics, or to compute
many metrics at once (e.g. the mean absolute error, or root mean squared error).

The `tidymodels` set of packages is designed for modelling in a consistent and tidy
fashion. The idea is that it abstracts (where appropriate) the specific syntaxes for
fitting different models and provides a common interface that generally works across
lots of different model types. It also has packages for data processing and model
evaluation, among other things.

We will be looking at just part of the `tidymodels` framework, and will be leaving
some of the more powerful aspects (e.g. workflows, model tuning etc) aside.

The packages we'll be focusing on are:

- `broom` for tidying up model output.
- `rsample` for resampling.
- `recipes` for data processing.
- `parsnip` for model fitting.
- `yardstick` for measuring model performance.

The [tidymodels website](https://tidymodels.org) has a number of excellent tutorials and an overview of some of the additional packages available (e.g. `tune`, `workshop`).

### Splitting data

